export const mockEvents = [
  {
    id: '1',
    title: 'Web3 Developer Conference',
    description: 'Learn about the latest in blockchain and Web3 technologies from industry experts.',
    date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    location: 'San Francisco, CA',
    price: 100,
    capacity: 500,
    category: 'TECH',
    isOnline: false,
    shareableUrl: 'web3-conf-2024',
    organizer: { id: 'org1', externalId: 'crypto_labs' },
    rsvps: [
      { id: 'rsvp1', userId: 'user1' },
      { id: 'rsvp2', userId: 'user2' },
    ],
  },
  {
    id: '2',
    title: 'Jazz Night Live',
    description: 'An evening of smooth jazz with local and international artists.',
    date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    location: 'Blue Note Jazz Club, NYC',
    price: 50,
    capacity: 200,
    category: 'ENTERTAINMENT',
    isOnline: false,
    shareableUrl: 'jazz-night-2024',
    organizer: { id: 'org2', externalId: 'blue_note' },
    rsvps: [
      { id: 'rsvp3', userId: 'user3' },
      { id: 'rsvp4', userId: 'user4' },
      { id: 'rsvp5', userId: 'user5' },
    ],
  },
  {
    id: '3',
    title: 'React Advanced Patterns Workshop',
    description: 'Master advanced React patterns with hands-on exercises and real-world examples.',
    date: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString(),
    location: 'Online',
    price: 75,
    capacity: 100,
    category: 'EDUCATION',
    isOnline: true,
    shareableUrl: 'react-workshop-2024',
    organizer: { id: 'org3', externalId: 'tech_academy' },
    rsvps: [{ id: 'rsvp6', userId: 'user6' }],
  },
  {
    id: '4',
    title: 'Summer Music Festival',
    description: 'Three days of live music featuring top artists across multiple genres.',
    date: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    location: 'Central Park, NYC',
    price: 150,
    capacity: 10000,
    category: 'ENTERTAINMENT',
    isOnline: false,
    shareableUrl: 'summer-fest-2024',
    organizer: { id: 'org4', externalId: 'live_events' },
    rsvps: [
      { id: 'rsvp7', userId: 'user1' },
      { id: 'rsvp8', userId: 'user7' },
      { id: 'rsvp9', userId: 'user8' },
      { id: 'rsvp10', userId: 'user9' },
    ],
  },
  {
    id: '5',
    title: 'Startup Networking Brunch',
    description: 'Connect with founders, investors, and entrepreneurs in the startup ecosystem.',
    date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    location: 'WeWork, San Francisco',
    price: 25,
    capacity: 150,
    category: 'BUSINESS',
    isOnline: false,
    shareableUrl: 'startup-brunch-2024',
    organizer: { id: 'org5', externalId: 'founder_hub' },
    rsvps: [
      { id: 'rsvp11', userId: 'user10' },
      { id: 'rsvp12', userId: 'user11' },
    ],
  },
  {
    id: '6',
    title: 'Digital Art Exhibition',
    description: 'Explore cutting-edge digital art installations and NFT collections.',
    date: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    location: 'Modern Art Museum, LA',
    price: 35,
    capacity: 300,
    category: 'ARTS',
    isOnline: false,
    shareableUrl: 'digital-art-2024',
    organizer: { id: 'org6', externalId: 'art_collective' },
    rsvps: [
      { id: 'rsvp13', userId: 'user12' },
      { id: 'rsvp14', userId: 'user13' },
      { id: 'rsvp15', userId: 'user14' },
    ],
  },
];

export const mockUsers = [
  {
    id: 'user1',
    externalId: 'john_doe',
    email: 'john@example.com',
    bearerToken: 'token_user1',
    riftUserId: 'rift_user1',
  },
  {
    id: 'user2',
    externalId: 'jane_smith',
    email: 'jane@example.com',
    bearerToken: 'token_user2',
    riftUserId: 'rift_user2',
  },
];
